[package]
name = "ocl"
version = "0.10.0"
authors = ["Nick Sanders <cogciprocate@gmail.com>"]
description = "OpenCL bindings and interfaces for Rust."
documentation = "http://doc.cogciprocate.com/ocl/ocl/index.html"
homepage = "https://github.com/cogciprocate/ocl"
repository = "https://github.com/cogciprocate/ocl"
readme = "README.md"
keywords = ["opencl", "gpu", "gpgpu"]
license = "MIT"
exclude = ["target/*", "*.png", "bak/*"]
build = "build.rs"

[features]
kernel_debug_print = []
kernel_debug_sleep = []

# [dependencies.bitflags]
# git = "https://github.com/rust-lang-nursery/bitflags.git"

[dependencies]
# [TODO]: Make optional feature:
rand = "0.3"
num = "0.1"
libc = "0.2"
enum_primitive = "0.1"
bitflags = "0.5"

[dev-dependencies]
# [TODO]: Make optional somehow or remove or something:
image = "0.7"
find_folder = "0.3"
colorify = "0.1"
time = "0.1"


[profile.test]
opt-level = 0
debug = true
rpath = false
lto = false
# Set false to make sure we're not relying overly on any debug assertions.
debug-assertions = false
codegen-units = 1

